modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="head_utils"
version="1.0.0"
displayName="Head Utils"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="OVONSAME"
description="A lightweight mod that adds functions to work with player's heads."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.head_utils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



